"""
config.py — Root dataset configuration parameters
"""
NUM_ACCOUNTS = 25000
NUM_TERMINALS = 2500
NUM_TRANSACTIONS = 250000

FRAUD_PERCENTAGE = 15

FAN_IN_SCENARIOS = 50
FAN_OUT_SCENARIOS = 50
LAYERING_SCENARIOS = 60
TRIADIC_SCENARIOS = 20

OUTPUT_DIR = "data/output"