NUM_ACCOUNTS = 200
NUM_TERMINALS = 50
NUM_TRANSACTIONS = 1000

FRAUD_PERCENTAGE = 15

FAN_IN_SCENARIOS = 2
FAN_OUT_SCENARIOS = 2
LAYERING_SCENARIOS = 2
TRIADIC_SCENARIOS = 1

OUTPUT_DIR = "data/output"